name: roonmatrix
version: '1.2.1'
summary: App to control your LED-matrix device
description: |
  App to control your own LED matrix hardware, which can display a wide range of informations: Music played from Roon, Apple Music or Spotify, weather data, RSS feeds, custom text messages, and more. The RoonMatrix is a free maker project, and describes step by step how to build your own LED matrix display hardware. And with this app you can configure your hardware extensively, and specify from which sources the text to display is composed. With the app you can send text messages directly to your device, control the display speed, brightness and much more.

title: roonmatrix
website: 
  - https://www.roonmatrix.com
contact: 
  - support@wilhelm-devblog.de
license: GPL-3.0+

base: core22
confinement: strict
grade: stable

apps:
  roonmatrix:
    command: roonmatrix
    extensions: [gnome]
    environment:
      GDK_BACKEND: x11
      GTK_MODULES: ""
      G_MESSAGES_DEBUG: ""
      G_LOG_LEVEL: "ERROR"
      NO_AT_BRIDGE: "1"
    plugs:
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - gsettings
      - icon-themes
      - gtk-3-themes
      - home
      - network
      - network-status
      - network-bind

parts:
  roonmatrix:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-snaps: [flutter/latest/stable]

    # This appears to be needed when building in the Snap Store.
    build-packages:
      - curl

architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]
